### ISSUE TITLE
Not able to make JDBC drivers work on Tableau Server

### ISSUE THREAD

**Issue by maurinLore** [tableau/connector-plugin-sdk#791] opened 2021-05-20 19:07 UTC
**About You:**
Name: Maurin Lenglart
Company: LoreIO

**Your question:**
Hi, 
I have created a .taco file for my company JDBC drivers. On my mac using tableau desktop it is working well, I am able to create charts and push them to tableau server. 
 But things are breaking when trying to access the charts from from tableau server. 
On my ubuntu tableau server (2021.1.0), I have added the .taco file to "/var/opt/tableau/tableau_server/data/tabsvc/vizqlserver/Connectors", and the JDBC driver to "/opt/tableau/tableau_driver/jdbc/" both have 755 access. 

Is there anything that I should add/change in my configuration ?
The following screenshot show the different errors that I see on tableau server: 

![Screen Shot 2021-04-20 at 3 06 10 PM](https://user-images.githubusercontent.com/84539504/119033657-52156700-b962-11eb-8640-b99490317b77.png)
![Screen Shot 2021-04-20 at 3 07 20 PM](https://user-images.githubusercontent.com/84539504/119033614-44f87800-b962-11eb-8b82-5d33ca8c9d60.png)
![Screen Shot 2021-04-20 at 3 05 59 PM](https://user-images.githubusercontent.com/84539504/119033655-517cd080-b962-11eb-9dee-0232ee0e1d86.png)

**Comment by jainam1995** [comment] 2021-05-20 19:38
Could you also confirm that the server is running on the same drive as the taco installed in as per the steps at https://tableau.github.io/connector-plugin-sdk/docs/run-taco under the section of setting up server.

**Comment by maurinLore** [comment] 2021-05-21 02:03
I can confirm.

**Comment by jainam1995** [comment] 2021-05-24 01:29
The error dialog says that the server is not licensed to connect to the datasource. @tsjoblad could you help regarding this licensing issue ?

**Comment by tsjoblad** [comment] 2021-05-24 16:01
Hi Maurin, can you please shoot me an email so we can confirm your licenses are set up ok?
tsjoblad@tableau.com

Thanks.

**Comment by tsjoblad** [comment] 2021-05-26 21:32
@jainam1995 I was able to confirm the licensing was not the root cause of the issue. Can you please reengage?

**Comment by jainam1995** [comment] 2021-05-26 23:04
Internal tracking issue : 1272416

**Comment by maurinLore** [comment] 2021-06-01 20:44
Hi, 
if that helps, I believe that the .taco is loaded properly on the server as I can see the connection details properly ( as seen in the screenshot bellow). Test is failing, with the error: "Could not connect to server" . But I have confirmed that the server on which tableau is installed is able to reach the server "dev01" properly. My guess is that the JDBC drivers are not getting recognized. 
As mentioned before the JDBC drivers are present in "/opt/tableau/tableau_driver/jdbc/" .

Thanks
<img width="458" alt="Screen Shot 2021-06-01 at 1 42 17 PM" src="https://user-images.githubusercontent.com/84539504/120387887-48cfb700-c2df-11eb-8b3e-33a3e111914b.png">

**Comment by pvanderknyff** [comment] 2021-06-21 23:40
Can you post clean logs for your server that shows the error in web authoring (trying to create or edit a workbook on server)? [This page](https://help.tableau.com/current/server/en-us/logs_loc.htm?_gl=1*1k9d8a*_ga*MTgzNTk4MDQ3OC4xNTk5MjUzMjYw*_ga_8YLN0SNXVS*MTYyNDMxODY5OS4zNS4xLjE2MjQzMTg3MDIuMA..) has instructions for getting the logs on server.

If you don't feel comfortable posting the logs to this thread, you can email them to me directly at pvanderknyff@tableau.com. Thanks!

**Comment by pvanderknyff** [comment] 2021-07-06 19:37
Closing for now. If you're still running into this issue, re-open the issue.

**Closed by pvanderknyff** 2021-07-06 19:37 UTC
