### ISSUE TITLE
Signature verification errors when running multiple threads on unsigned connector

### ISSUE THREAD

**Issue by sidwray** [tableau/connector-plugin-sdk#746] opened 2021-03-16 21:10 UTC
Question from the Dremio team. 

I needed to run TDVT in the same time zone as my Dremio instance (both UTC). I got sporadic connector signature verification errors when using multiple threads and an unsigned connector so for this run I set it to use a single thread.

**Comment by sxlin** [comment] 2021-03-29 17:50
@sidwray Can you get steps from Dremio team to reproduce this issue?

**Comment by jduo** [comment] 2021-04-12 20:50
Hi,
I ran TDVT with the default options for threads and would get errors occasionally. When I forced TDVT to use only a single thread the issues didn't occur.

The UTC issue is a bug on the Dremio driver side that is being fixed.

**Comment by sxlin** [comment] 2021-04-29 22:56
Signature verification code suppose not to run when we set `-DDisableVerifyConnectorPluginSignature=true` in CommandLineOverride.

I was not able to reproduce this issue on Windows or Mac.  I discussed this issue with Dremio, I will close this issue now.  We can reopen it when Dremio is able to reproduce this issue.

**Closed by sxlin** 2021-04-29 22:56 UTC

**Comment by jayhomn-bitquill** [comment] 2021-05-19 20:36
Hi,
I am not sure if it is exactly to same problem as I was not getting any errors but when I ran TDVT with default thread options, the tests would hang and never finish in the terminal. However, if I set the MaxThread option to 1, the tests completes.
