### ISSUE TITLE
[BUG] TDVT failures starting from 2020.3

### ISSUE THREAD

**Issue by CJStuart** [tableau/connector-plugin-sdk#614] opened 2020-09-22 13:45 UTC
**Describe the bug**
In the 2020.3 Beta, as part of the QA process, we ran the TDVT suite against our connector, which passed successfully, other than an expected failure of 'time1'.

Testing again against the 2020.3 GA release, we're seeing the following *new* failures:

```
DATEDIFF('week', [date2], #2050-01-01#)
DATEDIFF('week', [date3], [date2])
DATEDIFF('week', DATETIME([date2]), [datetime0])
DATENAME('week', [date2])
DATENAME('week', [datetime0])
DATEPART('week', [date2])
DATEPART('week', DATE([date3]))
DATEPART('week', [datetime0])
DATETRUNC('week', [date2])
DATETRUNC('week', [datetime0])
```

The full test results can be found here: 
[test_results_combined.csv.zip](https://github.com/tableau/connector-plugin-sdk/files/5261844/test_results_combined.csv.zip)

As far as we're aware, there haven't been any changes to the Databricks dialect from 2020.3 Beta to 2020.3, and we're also not seeing any relevant changes in the TDVT suite. Have there been any relevant changes in the Hive dialect that's used as a base class or in the semantics of week expressions?

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: 2020.3s
- TDVT Version: 2.1.15

**About you:**
 Name: Christian Stuart
 Company: Databricks

**Comment by sidwray** [comment] 2020-10-19 20:16
Note from @erademacher:
Nothing obvious has changed in that timeframe. Can Databricks provide a test result file from a 2020.2 run? Every test failure they're reporting revolves around date functions that use weeks. Are they arguing that the tests should pass?

**Comment by CJStuart** [comment] 2020-10-22 11:07
Rerunning the tests for 2020.2 results in the same failures that we didn't see before. I have attached the results of the tests we ran in april for the 2020.2 beta QA, where the tests passed, as well as the same tests that we ran today against 2020.2.6, where they failed. 

A notable difference, taking test case `DATEDIFF('week', [date2], #2050-01-01#)` as example, it used to succeed running:
> ```sql
> SELECT FLOOR(DATEDIFF(NEXT_DAY(CAST('2050-01-01' AS DATE),'SU'),NEXT_DAY(`calcs`.`date2`,'SU'))/7) AS `temp_test__2771060545__0_`
> FROM `tableau_tdvt`.`calcs` `calcs`
> GROUP BY 1
> ```

Whereas now it fails with off-by-one errors taking 'mo' instead of 'su' as the start of the week:

> ```sql
> SELECT FLOOR(DATEDIFF(NEXT_DAY(CAST('2050-01-01' AS DATE),'MO'),NEXT_DAY(`calcs`.`date2`,'MO'))/7) AS `temp_test__2771060545__0_`
> FROM `tableau_tdvt`.`calcs` `calcs`
> GROUP BY 1
> ``` 

This seems to be a pattern for all the failing tests. 

[TDVT_2020.2_diff.zip](https://github.com/tableau/connector-plugin-sdk/files/5422213/TDVT_2020.2_diff.zip)

**Comment by CJStuart** [comment] 2020-10-22 11:19
Looking into the base Hive dialect and ours, it appears these formulas are part of our dialect spec. To our knowledge nothing has changed there between these versions. Did the semantics of the dialect specification change in this time frame?

**Comment by erademacher** [comment] 2020-11-05 00:18
Hi Christian. Thanks for your patience.

I don't see anything seemingly relevant that changed in our codebase in that timeframe. There was a bug fix around date functions with a custom start-of-week that was made in July 2019, while this was all still in active development, but that should've shipped long before the 2020.3 beta.

I think you should be able to add `<start-of-week-offset value='6'>` to your .tdd file. If that doesn't work, please send us your dialect file and I'll be happy to troubleshoot.

**Comment by CJStuart** [comment] 2020-11-05 14:48
> I think you should be able to add <start-of-week-offset value='6'> to your .tdd file. If that doesn't work, please send us your dialect file and I'll be happy to troubleshoot.

Sadly that doesn't seem to help. The problem appears to be in the week formulas in the base dialect.

https://github.com/databricks/tableau-connector/commit/700821fdb74194ed21a2b091993b5902a9426ce1 is the version that is currently incorporated into Tableau, with this dialect:

https://github.com/databricks/tableau-connector/blob/700821fdb74194ed21a2b091993b5902a9426ce1/tableau-databricks/dialect.tdd

The last change to this file was in September 2019, so we're certain nothing changed on our side.

**Comment by sidwray** [comment] 2020-11-12 21:41
tfs 1197768

**Comment by bogdanghit** [comment] 2021-02-02 08:00
It seems those tests are failing when the testing machine is in a different timezone than the server. Is there a way we can set the timezone in the TDVT configuration? Other than that, I think we can close this ticket, thanks for investigating it!

**Comment by rosswbrown** [comment] 2021-02-02 17:09
Currently the Tableau [Date & Time](https://help.tableau.com/current/pro/desktop/en-us/datafields_typesandroles_datatypes.htm) type does not hold time zone information, so what you are observing is by design.  There are some [narrow](https://kb.tableau.com/articles/issue/unable-to-change-default-time-zone) workarounds for certain user scenarios, but for TDVT yes this is expected.

**Closed by rosswbrown** 2021-02-02 17:09 UTC
Labels: investigate
