### ISSUE TITLE
cannot edit datasource after clicking on sheet

### ISSUE THREAD

**Issue by saikeerthi733** [tableau/connector-plugin-sdk#618] opened 2020-09-24 04:40 UTC
**About You:**
Name: Venkata Sangaraju
Company: PayPal Inc

**Your question:**
Hi
I am seeing a strange issue with the SDK connector. After i establish connection to database using sdk connector and pulling some table and going to sheet, i see "Data Source" grade out. I am not able to go to datasource to modify sql or add more tables. We are on 2020.1.6 version. Can you please help us understand why its not going to data source section. Please see the screenshot
![image](https://user-images.githubusercontent.com/37277905/94101755-64e09780-fde5-11ea-9b55-86680ad279f7.png)

**Comment by saikeerthi733** [comment] 2020-10-14 01:05
any update on this? is it a bug on 2020.1 version or is there any tsm command? we just deployed the dremio connector and cannot go back to edit datasource after pulling tables once

**Comment by saikeerthi733** [comment] 2020-10-14 19:16
@saugatt @sidwray can someone help on this? Do we need to install anything else like java?

**Comment by rosswbrown** [comment] 2020-10-15 21:20
Hi, thanks for reporting.  This appears to be a functionality gap in 2020.1 and 2020.2.  We believe we have identified a fix for this that occurred in 2020.3, so you shouldn't see an issue in those newer releases.  

An item has been opened on our side to evaluate fixing this in the upcoming maintenance releases.  This issue will be updated when we can confirm a fix will be released.

**Comment by saikeerthi733** [comment] 2020-10-15 21:25
Thanks much for your response. Can you please give me an approximate date for the new maintenance release for our internal communications. Thanks again.

**Comment by jainam1995** [comment] 2020-10-21 23:19
The fix will be released as a part of the next 2020.1 maintenance release . Will update the ticket once the maintenance release is out

**Comment by venkatasangaraju** [comment] 2020-10-29 23:55
hi @jainam1995 today 2020.1.10 is released and we still see the same issue. Is there any workaround on the server we can do to make it work.

**Comment by venkatasangaraju** [comment] 2020-11-03 17:41
Hi @rosswbrown can you please help on this issue. I tested in 2020.1.10 but issue still persists. Is there any workaround to fix this issue. we have many users using sdk connector but cannot edit the datasource

**Comment by rosswbrown** [comment] 2020-11-04 16:05
Hi, the 2020.1.10 was locked for release before the change was made to resolve this.  The change mentioned above is slated for the next releases: 2020.1.11 and 2020.2.8.  We cannot commit to an exact release schedule, but you can see past history [here](https://www.tableau.com/support/releases).

The current workaround is to 2020.3 or newer releases.

**Comment by sidwray** [comment] 2020-11-12 21:40
tfs 1197785

**Comment by jainam1995** [comment] 2020-11-19 22:56
Hi @venkatasangaraju . Please could you try the latest Maintenance release : [https://www.tableau.com/support/releases/server/2020.1.11](https://www.tableau.com/support/releases/server/2020.1.11) and check if the issue has been fixed.

**Comment by venkatasangaraju** [comment] 2020-11-19 23:34
Hi @jainam1995 i have tested today in 2020.1.11 and the issue is resolved. thanks much for your support on this. closing this case.

**Closed** 2020-11-19 23:36 UTC
Labels: investigate
