### ISSUE TITLE
[QUESTION] "Timestamp with Time Zone" type using Presto/Trino connector

### ISSUE THREAD

**Issue by soydan** [tableau/connector-plugin-sdk#1064] opened 2023-02-01 09:46 UTC
Hi;
We are using the Presto Connector & Trino jdbc driver to expose some data from Trino to Tableau Server. Everything seems ok except this one issue: Columns with "TIMESTAMP WITH TIME ZONE" (TimestampZ) type are imported as Strings by default, and when converted to DateTime in the gui, they end up in UTC. (Tableau inserts CAST(col AS TIMESTAMP)). We would prefer these to be shown in local timezone as TimestampZ implies.

In order to better understand whether that was possible, I set up another database which has timestamp types both with and without Time Zone (TimestampZ/Timestamp): PostgreSQL. I connected it using the postgres jdbc driver and voila, TimestampZ fields are displayed in local Timezone in Tableau.

So my understanding is; this is somewhat possible with some changes in the Connector (and maybe in the jdbc driver as well). My first guess was that TimestampZ does not have a local - remote type mapping in the dialect file which results in it being interpreted as String. However; Presto's dialect file does not seem to be public so I can not confirm this. I was also not able to find dialect files that contain both Timestamp/TimestampZ to use as an example, PostgreSQL is not public, public ones do not seem to have TimestampZ type.

So if my approach is not wrong so far, here is the actual question: If I was to use Presto dialect as base, can I simply add a new local - remote type mapping under `<format-column-definition> `and expect it to work? Does dialect files support that sort of override behavior for that specific element, or do I have to start from scratch? 
Thanks & sorry if my approach is totally wrong.

**Comment by xsgao-github** [comment] 2023-02-09 19:55
You can use `<dialect name='TrinoDialect' base='PrestoDialect'`, putting your connector on top of Presto without knowing its full `dialect.tdd`.

**Comment by soydan** [comment] 2023-02-10 12:35
Hi Xsgao;
I know a base Dialect can be extended, but if I am not gong to be able to override `<format-column-definition>` element in my extended dialect, it's no use. (There isn't much info on how this can be achieved, that's why opened the question. Maybe I should just try it at this point). If it doesn't work, I would then have to start from scratch, in which case PrestoDialect would help as an example.
Btw., I noticed you are working with the Starburst driver. Isn't it also the same over there? (Assuming you are extending the already existing PrestoDialect). TimestampZ -> converted to String in Tableau by default.

**Comment by xsgao-github** [comment] 2023-02-10 15:02
> I am not gong to be able to override `<format-column-definition>` element in my extended dialect, it's no use
How did you get the conclusion? Did you try it?

Unfortunately, our connector also returns varchar for `date/timestamp with time zone`. But I see JDBC driver returns correct metadata, so I think this is a connector issue.

**Comment by soydan** [comment] 2023-02-10 16:08
Hi Xsgao;
I didn't write "it's not going to work"  but "**IF** it's not going to work". I have no idea, I didn't try it. The reason why I opened the question was maybe somebody with more knowledge on the SDK could tell if it's going to work or not, saving me the hassle in case it's a dead end. (I don't have the dev. environment set up) 

> I think this is a connector issue.
I think so too, and there is actually a connector that handles both timestamp and timestamp with timezone correctly (or rather the way I expect) -> PostgresSQL Connector. But it's dialect file is not open.
My guess is that under the `<format-column-definition>`, both timestamp and timestampZ are mapped to Tableau internal DateTime type. And the rest is up to the implementation in the jdbc driver (Coercion of timestampZ to timestamp)

Anyway, it looks like I will have to try and see whether it works when I have the time.

**Comment by jie-d** [comment] 2023-06-06 21:05
Hi @soydan, connection to a Trino server from Tableau should use the Starburst Connector (please find the Starburst Enterprise by Starburst under Additional Connectors) and trino driver. The Presto Connector should only be used to connect to a PrestoDB server, using the prestodb driver. Can you try again with the Starburst Connector?

By design, in JDBC connections, timestamp with time zone values should be resolved in local time zone by Tableau, like what you observed with PosgreSQL. I tested with both combinations mentioned above and didn't notice any different behavior. Essentially we are using [SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) to format the String outputted and it uses the default local time zone reported by the operating system. From my testing, the behavior of both drivers match this statement.

If you are still noticing unexpected behavior with the Starburst Connector, can you share some screenshots or logs of what you see so I can further assist? Thanks!

**Comment by jie-d** [comment] 2023-06-14 02:25
Closing the issue as no response after a week. Please open a new issue if there is more question.

**Closed by jie-d** 2023-06-14 02:25 UTC
