### ISSUE TITLE
[BUG] TDVT - Smoke tests failing

### ISSUE THREAD

**Issue by KKcorps** [tableau/connector-plugin-sdk#921] opened 2022-02-14 11:42 UTC
**About You:**
Name: Kartik Khare
Company: NA

**Your question:**
My smoke tests are failing when using my JDBC plugin. The error I get in the logs is - 
`Unable to establish connection: Data source 'Other Databases (JDBC)' has not been licensed.`

I can see the license is indeed valid in Tableau Desktop and I am able to query the same datasource using JDBC in tableau desktop. I looked into the past issues and lowered the `MaxThreads` to 1 as well but error still remained.

I am using the following - 

- MacOS Monterey
- Tableau Desktop 2021.4
- Python version 3.9
- tdvt build from master branch
- Staples and cast_calcs datasets

Command - ` /usr/local/opt/python@3.9/libexec/bin/python -m tdvt.tdvt run mydb `

```
Running tdvt suite [mydb]: tested sql [False]: tested tuples [True]: tested error [False]: output dir [/tmp/3ea43f67ea98e10abd0397eeb0767caae100232a46a65411833e4f25fpra1wci]: logical [True]: config file [StaplesConnectionTestmydb]: override [-DLogLevel=Debug]: tds [Staples.mydb.tds]: thread [6] tdvt thread id: 5

2022-02-11 17:27:57,645 Thread-[5] Running test:StaplesConnectionTestmydb
2022-02-11 17:27:57,653 Thread-[5]  calling /Applications/Tableau Desktop 2021.2.app/Contents/MacOS/tabquerytool --query-file-list /tmp/3ea43f67ea98e10abd0397eeb0767caae100232a46a65411833e4f25fpra1wci/StaplesConnectionTestmydb/tests.txt -d /Users/kharekartik/Documents/Packages/tableau-tests/tds/Staples.mydb.tds --combined --output-dir /tmp/3ea43f67ea98e10abd0397eeb0767caae100232a46a65411833e4f25fpra1wci -DLogDir=/tmp/3ea43f67ea98e10abd0397eeb0767caae100232a46a65411833e4f25fpra1wci/StaplesConnectionTestmydb -DOverride=ProtocolServerNewLog -DLogLevel=Debug -DLogicalQueryRewriteDisable=Funcall:RewriteConstantFuncall -DInMemoryLogicalCacheDisable
2022-02-11 17:28:05,993 Thread-[5] CalledProcessError: Return code: 17 LoadDatasource TableauException: Unable to establish connection: Data source 'Other Databases (JDBC)' has not been licensed.

No data source specified

2022-02-11 17:28:05,994 Thread-[5] Command line output:LoadDatasource TableauException: Unable to establish connection: Data source 'Other Databases (JDBC)' has not been licensed.
```

**Comment by pvanderknyff** [comment] 2022-03-09 17:10
Hi Kartik,

It looks like your TDVT tests are running against Other JDBC, not your new connector. You should re-generate your Calc and Staples TDS files by connecting to each table using your new connector, right-clicking on the connection in the Data pane, and selecting "Add to saved Datasources".

Let us know if the above, coupled with setting MaxThreads to 1 as you've already done, doesn't solve the issue. Thanks!

**Comment by pvanderknyff** [comment] 2022-03-21 21:02
Hi Kartik, we have reproduced this issue internally with Tableau 2021.4. As a workaround until this is fixed, try using 2021.3 or earlier.

**Comment by sxlin** [comment] 2022-04-01 22:03
@KKcorps 
Can you try the following steps?
1. Run command `atrdiag  -enableATRFeature`
2. Run command `atrdiag  -deleteAllATRs`
3. Start Tableau, you might see dialog says licensing changed, need restart, just let it restart
5. Run TDVT again. 

If you still see issue, please share the log with us.

**Comment by KKcorps** [comment] 2022-04-02 13:12
Thanks a lot. I'll update you in a day if this works or not.

**Comment by sxlin** [comment] 2022-04-12 17:34
@KKcorps Any update?

**Comment by sxlin** [comment] 2022-04-19 18:40
@KKcorps I am closing this old ticket.  Feel free to reopen if you still have issue.

**Closed by sxlin** 2022-04-19 18:40 UTC
