### ISSUE TITLE
All test cases are not running in TDVT 2.1.20

### ISSUE THREAD

**Issue by PiraisudanM** [tableau/connector-plugin-sdk#620] opened 2020-09-28 14:58 UTC
**About:**
Name: Piraisudan M.
Company: Guidanz.

**Question:**
Hi Team, we started integrating Tableau connector SDK with our BI Connector (ODBC based driver). We are facing the following issues:

1. We tried using TDVT SDK 2.1.20, but all the TDVT tests fail with **"No tests found. Check arguments."** error message (including smoke tests). Followed the steps mentioned in the TDVT document (https://tableau.github.io/connector-plugin-sdk/docs/tdvt)
But for the same configuration, the test cases are running in the TDVT SDK version 2.1.6.

2. Earlier we used "**DefaultSQLDialect**" as a base dialect in the "**dialect.tdd**" file. But currently, it is missing under the "Dialect base classes" in the TDVT document (https://tableau.github.io/connector-plugin-sdk/docs/design). When using a dialect other than DefaultSQLDialect, the success rate is far less. 
Can we continue using "DefaultSQLDialect" as the base dialect?

Since BI Connector is an "**Other Database(ODBC)**" based driver, can you please suggest any base dialect for "Other Database(ODBC)" in connector SDK? The rest of the dialects mentioned in the TDVT document doesn't seem to be appropriate for "Other Database(ODBC)".

**Comment by erademacher** [comment] 2020-09-28 18:09
Hi Piraisudan,

Thank you for raising these issues. I'm going to start looking into the "No tests found" issue immediately. **In the meantime, please use SDK version 2.1.18.**

Regarding the use of DefaultSQLDialect, we're currently recommending that SDK users omit the base dialect instead of using DefaultSQLDialect. Our suggestion is to start with full_dialect.tdd and make edits where appropriate. DefaultSQLDialect is still available to use, but it has some issues that might lead to unexpected test failures.

We appreciate your feedback. I'll update this issue when I have more information about the missing test error.

Evan

**Comment by PiraisudanM** [comment] 2020-09-29 12:26
Hi Evan,

Thank you for your prompt response.

As suggested, tried with the SDK version 2.1.18, but facing the same "No tests found. Check arguments." issue as mentioned earlier. 
Currently, I'm continuing with **SDK version 2.1.6** to run the test cases.

Please keep us posted on further updates.

**Comment by PiraisudanM** [comment] 2020-10-16 17:50
Hi Evan, 
Hope you are doing well.

Do you have any update on this issue?

**Comment by erademacher** [comment] 2020-10-19 20:33
Hi Piraisudan,

I believe this issue should be fixed in TDVT 2.1.21 and later. Could you please try upgrading to the latest version of TDVT? If the issue persists, could you please attach the test configuration file (.ini) that you're using?

Evan

**Comment by PiraisudanM** [comment] 2020-10-20 08:57
Hi Evan,
Thank you for your response.

**Issue - 1:**
As suggested, tried with the latest version of TDVT (v2.1.22), still facing the same "**No tests found. Check arguments**" issue. The same configuration works in 2.1.6. Please find the attached test configuration file as requested: 
[config.zip](https://github.com/tableau/connector-plugin-sdk/files/5407503/config.zip)

**Issue - 2:**
Our database doesn’t have the native boolean type support. So followed the steps mentioned under the "**Boolean data types are not recognized or your database doesn’t support them**" section from [TDVT](https://tableau.github.io/connector-plugin-sdk/docs/tdvt) document.

After re-mapping the boolean type columns in the TDS file, only the FALSE value is returned for all the boolean results in the "**Actual**", as shown in the below screenshot. 

![Boolean_TDVT](https://user-images.githubusercontent.com/29723277/96563768-f9a0bd00-12df-11eb-9039-70c1f9f2895a.png)


But the query executed successfully and the expected result is properly returned as an integer type to the tableau. This issue persists in all versions of TDVT. 

Also, tried setting "**CAP_QUERY_BOOLEXPR_TO_INTEXPR**" to "**yes**" and "**no**" in the plugin "manifest.xml" file, but getting the same result. 

We are currently in the process of Tableau certification for our connector and we are working on it as a high priority. Can you please help us to resolve this issue at the earliest so that we will be able to move faster on this?

**Comment by erademacher** [comment] 2020-10-21 22:43
Thank you for the additional info, Piraisudan. I'll have to look into the boolean issues more closely when I get the chance, but for now, could you try removing the ConnectionTests portion of the config file? Truncate it after [UnionTests]. Please let me know if that allows the rest of the tests to run. You may need to run tdvt with the --generate flag after making changes to the config.

**Comment by PiraisudanM** [comment] 2020-10-22 13:42
Hi Evan,

Thank you for the quick workaround for the "**No tests found. Check arguments**" issue. After removing the "**ConnectionTests**" section in the config INI file, able to run the tests in the latest version of TDVT too.

Also, we have an additional note to the boolean issue mentioned earlier.
After remapping the boolean columns as mentioned in the "**Boolean data types are not recognized or your database doesn’t support them**" section from the [TDVT](https://tableau.github.io/connector-plugin-sdk/docs/tdvt) document, we are getting this "**Reference to undefined field [bool0]**" error (field name in the error message updated based on the corresponding column name) for all the boolean column test cases which were passed earlier successfully.

**Example Test Cases:** "COUNTD([bool0])", "bool0", "bool1", "FLOAT([bool0])" and similar cases.

Please keep us posted on further updates.

**Comment by erademacher** [comment] 2020-10-28 17:32
@pvanderknyff @jainam1995 @saugatt Could one of you guys please help Piraisudan with this boolean issue? I'm absolutely swamped right now. There might be some light TDS manipulation required.

**Comment by PiraisudanM** [comment] 2020-11-04 12:51
Hi Team, 

Any updates on this issue?

**Comment by erademacher** [comment] 2020-11-05 22:17
Hi Piraisudan,

Apologies for the delay. I'm going to give this priority. Could you please attach your TDS and connector manifest files? Just the TDS for Calcs is fine.

I don't think remapping boolean columns alone should have an impact on date/datetime boolean operators, but I'll need to take a look at the capabilities in play to get a good picture of what's going on.

**Comment by PiraisudanM** [comment] 2020-11-06 13:45
Hi Evan, 

Thank you for the update. 

Please find the attached "**manifest.xml**" and "**cast_calcs.biconnector_odbc.tds**" files as requested.
[Tableau_plugin_configuration.zip](https://github.com/tableau/connector-plugin-sdk/files/5501518/Tableau_plugin_configuration.zip)

Regarding the boolean data type issue, only the "**FALSE**" value is returned for all the test cases (irrespective of the argument's data type) which require boolean results in the "**Actual**", as shown in the below screenshots.

![2020-11-06_19h00_16](https://user-images.githubusercontent.com/29723277/98372721-369cdb80-2064-11eb-9894-31a2e1f35222.png)
![2020-11-06_19h02_51](https://user-images.githubusercontent.com/29723277/98372737-3d2b5300-2064-11eb-9be0-a4c874a7e7f6.png)

Please keep us posted on further updates.

**Comment by erademacher** [comment] 2020-11-06 21:27
Thank you, Piraisudan. Everything looks like it's been correctly set up as far as the boolean columns go. I'm curious about what your database is sending back in the result set, though. What are the respective integer values it's returning for true and false?

Could you please send the full test_results.csv file so that I can take a look at exactly what queries Tableau is sending and what the full Actual datasets look like? And just to eliminate any other potential back-and-forth, it may be helpful if you can just go ahead and send over the .tdd file as well.

Thanks for your patience and cooperation.

**Comment by PiraisudanM** [comment] 2020-11-07 14:25
Hi Evan,

Thank you for the update.

In a result set, 1 is returned for **true** and 0 is returned for **false**.

Please find the attached "**test_results_combined.csv**" and "**dialect.tdd**" files as requested.  
[tableau_test_results_dialect_files.zip](https://github.com/tableau/connector-plugin-sdk/files/5504883/tableau_test_results_dialect_files.zip)

**Comment by erademacher** [comment] 2020-11-12 00:16
Hi Piraisudan,

Sorry, but I'm having trouble reproducing this issue internally. Int values of 0 and 1 are bound as SQL_C_TINYINT and interpreted by Tableau as false and true, respectively. The fact that a test like operator.bool/TRUE (which is basically just SELECT 1) fails suggests that something might be going wrong in the data binding phase. Clearly other tests that return integers are passing, so I'm wondering if there may be something wrong with the TINYINT wire type.

Could you please send logs and an ODBC trace from a TDVT run? To get a clean set of logs, first clear out your My Tableau Repository/Logs folder, then run the tests, and finally zip and send the contents of that Logs folder.

Thanks for your continued cooperation.

**Comment by PiraisudanM** [comment] 2020-11-12 15:46
Hi Evan,

Thank you for the update.

As mentioned, cleared the log files under the "**My Tableau Repository/Logs**" folder, only an empty "**crashdumps**" folder was created under this folder.
After running the TDVT tests, the "**tabquery_logs.zip**" folder was generated under the TDVT workspace.

Please find the attached log files generated. Let me know if you need any additional information. 
[tabquery_logs.zip](https://github.com/tableau/connector-plugin-sdk/files/5531643/tabquery_logs.zip)
[tdvt_log_combined.txt](https://github.com/tableau/connector-plugin-sdk/files/5531644/tdvt_log_combined.txt)

**Comment by sidwray** [comment] 2020-11-12 21:38
tfs 1197784

**Comment by erademacher** [comment] 2020-11-13 00:02
Hi Piraisudan,

Thanks for sending those logs. Unfortunately, I don't see anything unusual yet. I'm going to brainstorm some next steps and get back to you tomorrow morning.

**Comment by erademacher** [comment] 2020-11-23 23:50
Hi Piraisudan,

I'm glad we were able to work around the original "no tests found" issue earlier, and that we were able to sync up on the boolean issue outside of GitHub. I'm going to close this issue. I've created an internal defect for fixing the root cause of the "no tests found" issue. Please monitor the release notes if you're interested in tracking the fix. Thanks again for all your cooperation!

Evan

**Closed by erademacher** 2020-11-23 23:50 UTC
Labels: investigate
