### ISSUE TITLE
More visibility on "Tableau was unable to generate a query to perform this operation"

### ISSUE THREAD

**Issue by luigidellaquila** [tableau/connector-plugin-sdk#1031] opened 2022-11-03 08:05 UTC
**About You:**
Name: Luigi Dell'Aquila
Company: Elastic

**Your question:**
Hi all,

Since Elastic JDBC does not support full SQL feature set, we sometimes end up receiving "Tableau was unable to generate a query to perform this operation" errors. 
In most of the cases, the dialog does not return much information about the actual cause of the error. From the logs we can get the logical query, but often it is not clear which is the actual reason for the error.
Is there anything we can do to have more specific clues? It would be cool to have a pointer to which missing feature in SQL is preventing the query from being executed.
This would help us a lot to understand if specific errors are due to bugs (either ES or Tableau side) or if it's just a lack of capabilities in our SQL.

Thanks

Luigi

**Comment by jeffmaddocks** [comment] 2022-11-03 16:41
We have identified an issue building a fairly basic Tableau viz on Elastic data, and are unable to debug where the issue lies without this additional logging. This problem will impact **all customers** who build a very basic visualization, such as Top 5 manufacturers by product category:

To reproduce:

Connect to the eCommerce dataset > drag Products.Category into Rows, then add Products.Manufacturer into Rows next to Procucts.Category. Drag Products.Quantity into Columns.

Now try to add a conditional filter onto the viz: drag Products.Manufacturer into the Filters box > choose Condition > By Field > Keep Products.Quantity > keep Sum > change the operator to Greater Than > Value = 200.

**Comment by luigidellaquila** [comment] 2022-11-04 10:05
We are having similar errors when trying to convert a query to custom SQL.
See attached screenshots, all we do is choose "Convert to Custom SQL" and click "OK" (no changes to the query).
Also in this case, Tableau does not give any information of what the actual problem is.

<img width="667" alt="Schermata 2022-11-04 alle 11 00 28" src="https://user-images.githubusercontent.com/459289/199946127-d87c0abb-536f-46f0-8106-3739ff79f6cb.png">

<img width="777" alt="Schermata 2022-11-04 alle 11 00 41" src="https://user-images.githubusercontent.com/459289/199946276-6e368566-9217-4d29-9a27-45c48ea5f4b5.png">


In the logs we see

```
{"ts":"2022-11-04T10:59:12.264","pid":74444,"tid":"1360a8","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"detailed-error-msg","e":{"excp-error-code":"0xBAD0A3FA","excp-source":"NeedsClassification","excp-status-code":"UNKNOWN"},"v":{"details":["Tableau was unable to generate a query to perform this operation."],"headline":"An error occurred while communicating with the data source","support-help-link":"https://www.tableau.com/en-us/app/producthelp?build=20221.22.0516.1720&edition=pro&errorcode=94f50e12&errormessage=&lang=en-us&platform=mac&type=redirect&version=2022.1"}}
```

**Comment by pvanderknyff** [comment] 2022-12-06 21:59
This error often means that Tableau was not able to compose a query because of conflicting capabilities or missing dialect functions. A common scenario is both subquery support and temp tables being turned off in the capabilities - you need one or the other for the connector to function (documented [here](https://tableau.github.io/connector-plugin-sdk/docs/design#set-connector-capabilities)). That'd be the first thing to check, before digging deeper into the dialect.

For the dialect, we strongly recommend starting from the complete dialect sample and modifying that rather than creating a dialect from scratch. The dialect included in the [postgres_jdbc sample](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_jdbc/dialect.tdd) is fully implemented and does not throw this error. I'd suggest comparing your dialect against that one and ensuring that all functions are implemented, or if you're early in development starting with a copy of the sample dialect and copying your modifications over. 

Closing this issue as resolved. If the steps above aren't enough to mitigate the issues you're facing, respond to this issue and we'll flag this as a possible feature request, which will be prioritized against existing features and maintenance on our backlog.

**Closed by pvanderknyff** 2022-12-06 21:59 UTC
